import { StyleSheet } from 'react-native';
import { palette } from '../auth/design';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  background: {
    ...StyleSheet.absoluteFill,
    backgroundColor: palette.background,
  },
  grid: {
    ...StyleSheet.absoluteFill,
    opacity: 0.15,
    borderWidth: 0.35,
    borderColor: '#1D4B76',
  },
  glowTop: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    top: -70,
    right: -90,
    backgroundColor: '#0D4B8A',
    opacity: 0.45,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 24,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  brandTiny: {
    color: palette.cyan,
    fontSize: 12,
    fontWeight: '700',
  },
  logoutBtn: {
    borderWidth: 1,
    borderColor: '#214F79',
    borderRadius: 999,
    backgroundColor: 'rgba(8, 33, 59, 0.94)',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  logoutText: {
    color: palette.slate,
    fontSize: 11,
    fontWeight: '700',
  },
  homeHero: {
    borderWidth: 1,
    borderColor: '#25537E',
    borderRadius: 16,
    backgroundColor: 'rgba(8, 32, 58, 0.84)',
    padding: 14,
    marginBottom: 12,
  },
  homeHeroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  homeHeroBrand: {
    color: palette.cyan,
    fontSize: 12,
    fontWeight: '700',
  },
  homeHeroTitle: {
    color: palette.white,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
    marginBottom: 8,
  },
  homeHeroDesc: {
    color: palette.slate,
    fontSize: 13,
    lineHeight: 19,
  },
  homeStatRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  homeStatCard: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#214F79',
    backgroundColor: 'rgba(8, 34, 62, 0.9)',
    padding: 12,
  },
  homeStatValue: {
    color: palette.white,
    fontSize: 20,
    fontWeight: '800',
  },
  homeStatLabel: {
    color: palette.slate,
    fontSize: 11,
    marginTop: 4,
  },
  homeSectionTitle: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
  },
  homeCard: {
    borderWidth: 1,
    borderColor: '#214F79',
    borderRadius: 12,
    backgroundColor: 'rgba(9, 33, 59, 0.88)',
    padding: 12,
    marginBottom: 10,
    gap: 8,
  },
  homeCardTitle: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '700',
  },
  homeCardSubtitle: {
    color: palette.slate,
    fontSize: 12,
  },
  cameraCard: {
    borderWidth: 1,
    borderColor: '#214F79',
    borderRadius: 12,
    backgroundColor: 'rgba(9, 33, 59, 0.88)',
    marginBottom: 12,
    overflow: 'hidden',
  },
  cameraImage: {
    height: 150,
    backgroundColor: '#12283E',
  },
  cameraMeta: {
    padding: 10,
    gap: 8,
  },
  cameraName: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '700',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  pillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  cameraFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cameraFooterText: {
    color: palette.slate,
    fontSize: 11,
  },
  listCard: {
    borderWidth: 1,
    borderColor: '#214F79',
    borderRadius: 12,
    backgroundColor: 'rgba(9, 33, 59, 0.88)',
    marginBottom: 10,
    padding: 12,
    gap: 8,
  },
  cameraListRow: {
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(33,79,121,0.55)',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  cameraListMain: {
    flex: 1,
    gap: 2,
  },
  cameraListName: {
    color: palette.white,
    fontSize: 13,
    fontWeight: '700',
  },
  cameraListMeta: {
    color: palette.slate,
    fontSize: 11,
  },
  actionBtn: {
    borderWidth: 1,
    borderColor: '#2A4E74',
    borderRadius: 999,
    backgroundColor: 'rgba(10, 25, 46, 0.6)',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  actionBtnText: {
    color: palette.cyan,
    fontSize: 11,
    fontWeight: '700',
  },
  weatherLogRow: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(33,79,121,0.55)',
    gap: 2,
    paddingTop: 8,
  },
  weatherLogName: {
    color: palette.white,
    fontSize: 12,
    fontWeight: '700',
  },
  weatherLogMeta: {
    color: palette.slate,
    fontSize: 11,
  },
});
