import { StyleSheet } from 'react-native';
import { palette } from '../auth/design';

export const entryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#03142A',
  },
  background: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#03142A',
  },
  grid: {
    ...StyleSheet.absoluteFill,
    opacity: 0.14,
    borderWidth: 0.35,
    borderColor: '#1A4B76',
  },
  glowLeft: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    left: -120,
    top: 110,
    backgroundColor: '#0B8E8A',
    opacity: 0.18,
  },
  glowRight: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 180,
    right: -120,
    top: -80,
    backgroundColor: '#134A8A',
    opacity: 0.35,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  centerWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  haloOuter: {
    width: 110,
    height: 110,
    borderRadius: 55,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,242,234,0.12)',
  },
  haloInner: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(18,40,71,0.95)',
    borderWidth: 1,
    borderColor: '#2C5B84',
  },
  brandName: {
    marginTop: 18,
    color: palette.cyan,
    fontSize: 48,
    fontWeight: '800',
  },
  brandSubtitle: {
    marginTop: 8,
    color: '#AFC2D7',
    fontSize: 18,
    textAlign: 'center',
  },
  buttonPrimary: {
    marginTop: 32,
    width: '100%',
    minHeight: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.cyan,
    shadowColor: palette.cyan,
    shadowOpacity: 0.4,
    shadowRadius: 14,
  },
  buttonPrimaryText: {
    color: '#053C47',
    fontSize: 31,
    fontWeight: '700',
  },
  buttonSecondary: {
    marginTop: 14,
    width: '100%',
    minHeight: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2A4E74',
    backgroundColor: 'rgba(10, 25, 46, 0.45)',
  },
  buttonSecondaryText: {
    color: '#D5E2F0',
    fontSize: 28,
    fontWeight: '600',
  },
  helperText: {
    marginTop: 22,
    color: '#7A8FA8',
    fontSize: 12,
    textAlign: 'center',
  },
  onboardingImageWrap: {
    width: 290,
    height: 290,
    borderRadius: 145,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2A557C',
    backgroundColor: 'rgba(9, 32, 57, 0.72)',
    alignSelf: 'center',
    marginTop: 12,
  },
  onboardingDash: {
    position: 'absolute',
    width: 176,
    height: 8,
    borderRadius: 4,
    backgroundColor: palette.cyan,
    transform: [{ rotate: '-36deg' }],
  },
  chip: {
    position: 'absolute',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  chipDanger: {
    borderColor: 'rgba(239,68,68,0.35)',
    backgroundColor: 'rgba(127,29,29,0.36)',
  },
  chipWarn: {
    borderColor: 'rgba(245,158,11,0.45)',
    backgroundColor: 'rgba(120,53,15,0.4)',
  },
  chipSafe: {
    borderColor: 'rgba(16,185,129,0.35)',
    backgroundColor: 'rgba(6,78,59,0.4)',
  },
  chipText: {
    color: '#DCE8F6',
    fontSize: 12,
    fontWeight: '700',
  },
  slideTitle: {
    marginTop: 30,
    color: palette.white,
    fontSize: 44,
    lineHeight: 52,
    textAlign: 'center',
    fontWeight: '800',
  },
  slideAccent: {
    color: palette.cyan,
  },
  slideDesc: {
    marginTop: 14,
    color: '#AABFD5',
    fontSize: 17,
    lineHeight: 26,
    textAlign: 'center',
  },
  dotsRow: {
    marginTop: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#35506C',
  },
  dotActive: {
    width: 30,
    borderRadius: 8,
    backgroundColor: palette.cyan,
  },
  permissionCard: {
    marginTop: 24,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#2B557C',
    backgroundColor: 'rgba(13, 35, 60, 0.86)',
    padding: 18,
    gap: 14,
  },
  permissionTitle: {
    color: '#D7E5F5',
    fontSize: 40,
    textAlign: 'center',
    fontWeight: '800',
  },
  permissionDesc: {
    color: '#9DB4CB',
    fontSize: 17,
    lineHeight: 26,
    textAlign: 'center',
  },
  badge: {
    alignSelf: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#294C71',
    backgroundColor: 'rgba(9, 30, 54, 0.86)',
    paddingHorizontal: 14,
    paddingVertical: 5,
  },
  badgeText: {
    color: palette.cyan,
    fontSize: 14,
    fontStyle: 'italic',
    fontWeight: '700',
  },
});
