import { StyleSheet } from 'react-native';

export const palette = {
  cyan: '#00F2EA',
  blue: '#3B82F6',
  emerald: '#10B981',
  slate: '#94A3B8',
  background: '#03142A',
  panel: '#0C223F',
  panelBorder: '#163A63',
  white: '#EAF6FF',
  danger: '#EF4444',
} as const;

export const authStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  pageWrap: {
    flex: 1,
    minHeight: 690,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFill,
    backgroundColor: palette.background,
  },
  grid: {
    ...StyleSheet.absoluteFill,
    opacity: 0.16,
    borderWidth: 0.4,
    borderColor: '#1B4E7D',
  },
  glowTop: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    top: -88,
    right: -84,
    backgroundColor: '#134A8A',
    opacity: 0.55,
  },
  glowMiddle: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    top: 172,
    left: -76,
    backgroundColor: '#0B8E8A',
    opacity: 0.24,
  },
  authHeader: {
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    marginBottom: 16,
  },
  pinIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1F4A77',
    backgroundColor: 'rgba(10, 34, 59, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinIcon: {
    color: palette.cyan,
    fontSize: 24,
    fontWeight: '700',
  },
  brandName: {
    color: palette.cyan,
    fontSize: 37,
    lineHeight: 43,
    textAlign: 'center',
    fontWeight: '800',
  },
  authSubtitle: {
    color: palette.slate,
    textAlign: 'center',
    fontSize: 14,
  },
  authSubtitleSerif: {
    color: '#C4D3E4',
    textAlign: 'center',
    fontSize: 17,
    lineHeight: 26,
    fontWeight: '500',
  },
  sourceText: {
    marginTop: 24,
    color: '#8098B3',
    textAlign: 'center',
    fontSize: 12,
  },
  authCard: {
    borderWidth: 1,
    borderColor: '#224F7A',
    borderRadius: 16,
    backgroundColor: 'rgba(9, 33, 58, 0.88)',
    padding: 14,
    gap: 12,
  },
  authCardGlow: {
    shadowColor: '#00F2EA',
    shadowOpacity: 0.22,
    shadowRadius: 22,
  },
  authCardLarge: {
    padding: 24,
    gap: 16,
  },
  authCardCentered: {
    marginTop: 70,
  },
  authScreenFooter: {
    marginTop: 28,
    borderWidth: 1,
    borderColor: '#234D75',
    borderRadius: 16,
    backgroundColor: 'rgba(14,35,59,0.68)',
    padding: 18,
    gap: 8,
  },
  authScreenFooterTitle: {
    color: '#D7E5F5',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
  },
  authScreenFooterLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
  },
  authScreenFooterLinkText: {
    color: '#AABFD5',
    fontSize: 16,
  },
  authScreenFooterMeta: {
    marginTop: 2,
    color: '#8BA2BB',
    textAlign: 'center',
    fontSize: 14,
  },
  authCardHeader: {
    gap: 4,
    marginBottom: 2,
  },
  authCardTitle: {
    color: palette.white,
    fontSize: 18,
    fontWeight: '800',
  },
  authCardSubtitle: {
    color: palette.slate,
    fontSize: 12,
  },
  errorBanner: {
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.45)',
    borderRadius: 10,
    backgroundColor: 'rgba(127, 29, 29, 0.25)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  errorText: {
    color: '#FCA5A5',
    fontSize: 12,
  },
  successBanner: {
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.45)',
    borderRadius: 10,
    backgroundColor: 'rgba(6, 78, 59, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  successText: {
    color: '#6EE7B7',
    fontSize: 12,
  },
  fieldGroup: {
    gap: 6,
  },
  fieldLabel: {
    color: palette.slate,
    fontSize: 12,
    fontWeight: '600',
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2A587F',
    borderRadius: 12,
    backgroundColor: 'rgba(8, 30, 53, 0.9)',
    minHeight: 46,
    paddingHorizontal: 10,
    gap: 8,
  },
  inputWrapLarge: {
    minHeight: 58,
    borderRadius: 14,
  },
  inputIconWrap: {
    width: 20,
    alignItems: 'center',
  },
  inputIcon: {
    color: '#63C6D5',
    fontSize: 20,
    fontWeight: '600',
  },
  input: {
    flex: 1,
    color: palette.white,
    minHeight: 40,
    paddingHorizontal: 0,
    fontSize: 14,
  },
  inputLarge: {
    fontSize: 19,
    minHeight: 46,
  },
  subtleHint: {
    marginTop: -4,
    color: '#90A7BF',
    fontSize: 11,
  },
  hintRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  hintText: {
    color: palette.slate,
    fontSize: 11,
  },
  authSmallAction: {
    alignItems: 'flex-end',
  },
  authSmallActionText: {
    color: palette.slate,
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  authSwitchRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  authSwitchText: {
    color: palette.slate,
    fontSize: 16,
  },
  authSwitchAction: {
    color: palette.cyan,
    fontWeight: '700',
    fontSize: 16,
    textDecorationLine: 'underline',
  },
  primaryBtn: {
    backgroundColor: palette.cyan,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: palette.cyan,
    shadowOpacity: 0.48,
    shadowRadius: 14,
  },
  primaryBtnDisabled: {
    opacity: 0.55,
  },
  primaryBtnText: {
    color: '#003A3A',
    fontWeight: '700',
    fontSize: 18,
  },
  secondaryBtn: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2A4E74',
    backgroundColor: 'rgba(10, 25, 46, 0.6)',
    paddingVertical: 13,
    alignItems: 'center',
  },
  secondaryBtnText: {
    color: '#D4E2F1',
    fontSize: 16,
    fontWeight: '600',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(37, 76, 109, 0.65)',
  },
  dividerText: {
    color: '#57718B',
    fontSize: 11,
    letterSpacing: 1,
  },
  bottomBlock: {
    marginTop: 'auto',
    gap: 12,
    paddingBottom: 12,
  },
  tinyFooter: {
    color: '#6E88A8',
    fontSize: 10,
    lineHeight: 14,
    opacity: 0.95,
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.82,
  },
});
