// <auto-generated />
using System;
using HcmcRainVision.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HcmcRainVision.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204135807_SyncERD_WardOnly")]
    partial class SyncERD_WardOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.AlertSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Point>("CenterPoint")
                        .HasColumnType("geometry")
                        .HasColumnName("center_point");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int?>("RadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("radius_meters");

                    b.Property<float>("ThresholdProbability")
                        .HasColumnType("real")
                        .HasColumnName("threshold_probability");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("WardId")
                        .HasColumnType("text")
                        .HasColumnName("ward_id");

                    b.HasKey("SubscriptionId")
                        .HasName("pk_alert_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_alert_subscriptions_user_id");

                    b.HasIndex("WardId")
                        .HasDatabaseName("ix_alert_subscriptions_ward_id");

                    b.ToTable("alert_subscriptions");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.Camera", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRainAlertSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardId")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_cameras");

                    b.HasIndex("WardId")
                        .HasDatabaseName("ix_cameras_ward_id");

                    b.ToTable("cameras");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.CameraStatusLog", b =>
                {
                    b.Property<Guid>("StatusLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("status_log_id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("StatusLogId")
                        .HasName("pk_camera_status_logs");

                    b.HasIndex("CameraId")
                        .HasDatabaseName("ix_camera_status_logs_camera_id");

                    b.ToTable("camera_status_logs");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.CameraStream", b =>
                {
                    b.Property<Guid>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stream_id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_type");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_url");

                    b.HasKey("StreamId")
                        .HasName("pk_camera_streams");

                    b.HasIndex("CameraId")
                        .HasDatabaseName("ix_camera_streams_camera_id");

                    b.ToTable("camera_streams");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.FavoriteCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_favorite_cameras");

                    b.HasIndex("CameraId")
                        .HasDatabaseName("ix_favorite_cameras_camera_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_favorite_cameras_user_id");

                    b.ToTable("favorite_cameras");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.IngestionAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime>("AttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempt_at");

                    b.Property<string>("CameraId")
                        .HasColumnType("text")
                        .HasColumnName("camera_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AttemptId")
                        .HasName("pk_ingestion_attempts");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_ingestion_attempts_job_id");

                    b.ToTable("ingestion_attempts");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("JobId")
                        .HasName("pk_ingestion_jobs");

                    b.ToTable("ingestion_jobs");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.UserNotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterestedDistricts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_user_notification_settings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_notification_settings_user_id");

                    b.ToTable("user_notification_settings");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UserClaimIsRaining")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_user_reports");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_reports_user_id");

                    b.ToTable("user_reports");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.Ward", b =>
                {
                    b.Property<string>("WardId")
                        .HasColumnType("text")
                        .HasColumnName("ward_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward_name");

                    b.HasKey("WardId")
                        .HasName("pk_wards");

                    b.ToTable("wards");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.WeatherLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraId")
                        .HasColumnType("text");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsRaining")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("pk_weather_logs");

                    b.ToTable("weather_logs");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.AlertSubscription", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_subscriptions_users_user_id");

                    b.HasOne("HcmcRainVision.Backend.Models.Entities.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .HasConstraintName("fk_alert_subscriptions_wards_ward_id");

                    b.Navigation("User");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.Camera", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cameras_wards_ward_id");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.CameraStatusLog", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camera_status_logs_cameras_camera_id");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.CameraStream", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camera_streams_cameras_camera_id");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.FavoriteCamera", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_cameras_cameras_camera_id");

                    b.HasOne("HcmcRainVision.Backend.Models.Entities.User", "User")
                        .WithMany("FavoriteCameras")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_cameras_users_user_id");

                    b.Navigation("Camera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.IngestionAttempt", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.IngestionJob", "Job")
                        .WithMany("Attempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_attempts_ingestion_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.UserNotificationSetting", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.UserReport", b =>
                {
                    b.HasOne("HcmcRainVision.Backend.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_reports_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.IngestionJob", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("HcmcRainVision.Backend.Models.Entities.User", b =>
                {
                    b.Navigation("FavoriteCameras");
                });
#pragma warning restore 612, 618
        }
    }
}
